### ISSUE TITLE
Base94 conversion is not an actual one.

### ISSUE THREAD

**Issue by raxetul** [TheYkk/gkey#1]
Base94 conversion seems to make collisions and leverages sha256 output's security.
It may be enough for basic security but not for hardened exact one.

**Comment by TheYkk** [comment]
Base94 translate sha256 hex bytes to usable strong password
Example
Sha256 hex `199d9b3dfc22818e22b63b4243ac36a5ef3d5664feefcad06c0aac73858429fb`
Base94 `z$@0(IN1Ic8#$|3_80<k-8wCsk|zRQP*`

**Comment by raxetul** [comment]
Yes, passwords are strong but decoding of the password may not match sha256. So it is not an exact encoding, sha256 to 94 char conversion might be called "simple modulo hash".
